### ISSUE TITLE
'CLYPHX SNAP' tracks do not work

### ISSUE THREAD

**Issue by VegaDeftwing** [ldrolez/clyphx-live10#1]
working from master, not the latest release, in Live 11 it seems that while snap clips are working again in general, the 'CLYPHX SNAP' named tracks do not work at all, meaning there is no parameter morphing.

Thanks for maintaining and updating this to Live 11. Your work is really appreciated.

**Comment by ldrolez** [comment]
Many thanks for your report! In order to reproduce your exact problem, could you please provide step-by-step instructions or upload a basic .als file?

**Comment by VegaDeftwing** [comment]
I figured a video would probably be the easiest way to show it: https://www.youtube.com/watch?v=2spuhHNFlFE

**Comment by ldrolez** [comment]
Many thanks for your Video!

I reproduced your bug. Here are the error, now I have to understand what happens... 

```
2021-04-28T18:06:28.806227: info: Python: INFO:_Framework.ControlSurface:805 - LOG: (ClyphX) Error when executing task
2021-04-28T18:06:28.806293: info: RemoteScriptMessage: (ClyphX) Error when executing task
2021-04-28T18:06:28.822511: info: RemoteScriptError: Traceback (most recent call last):

2021-04-28T18:06:28.822700: info: RemoteScriptError: 
2021-04-28T18:06:28.822925: info: RemoteScriptError:   File "..\..\..\output\Live\win_64_static\Release\python-bundle\MIDI Remote Scripts\_Framework\Task.py", line 237, in do_update

2021-04-28T18:06:28.823062: info: RemoteScriptError: 
2021-04-28T18:06:28.823205: info: RemoteScriptError:   File "..\..\..\output\Live\win_64_static\Release\python-bundle\MIDI Remote Scripts\_Framework\Task.py", line 58, in update

2021-04-28T18:06:28.823334: info: RemoteScriptError: 
2021-04-28T18:06:28.823480: info: RemoteScriptError:   File "..\..\..\output\Live\win_64_static\Release\python-bundle\MIDI Remote Scripts\_Framework\Task.py", line 153, in do_update

2021-04-28T18:06:28.823623: info: RemoteScriptError: 
2021-04-28T18:06:28.823765: info: RemoteScriptError:   File "..\..\..\output\Live\win_64_static\Release\python-bundle\MIDI Remote Scripts\_Framework\ControlSurfaceComponent.py", line 196, in wrapper

2021-04-28T18:06:28.823893: info: RemoteScriptError: 
2021-04-28T18:06:28.824034: info: RemoteScriptError:   File "D:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts\ClyphX\ClyphXSnapActions9.py", line 369, in _on_timer
    self._apply_timed_smoothing()

2021-04-28T18:06:28.824159: info: RemoteScriptError: 
2021-04-28T18:06:28.824299: info: RemoteScriptError:   File "D:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts\ClyphX\ClyphXSnapActions9.py", line 391, in _apply_timed_smoothing
    for p, v in self._parameters_to_smooth.items():

2021-04-28T18:06:28.824434: info: RemoteScriptError: 
2021-04-28T18:06:28.824672: info: RemoteScriptError: RuntimeError: dictionary changed size during iteration

2021-04-28T18:06:28.824790: info: RemoteScriptError: 

```

**Comment by VegaDeftwing** [comment]
I know you closed the issue, but I thought I'd drop by to confirm the fix is working well! Thank you so much for the quick fix!
